using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SourceGeneration;

[Generator]
public sealed class ToolButtonGenerator : IIncrementalGenerator
{
    private const string DefinitionFqn = "Ciallo.Tool.ToolButton.DefinitionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<EnumModel?> enums = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is EnumDeclarationSyntax { AttributeLists.Count: 0 } or EnumDeclarationSyntax,
                transform: static (ctx, _) => GetEnum(ctx))
            .Where(static model => model is not null);

        context.RegisterSourceOutput(enums.Collect(), static (spc, collected) => Execute(spc, collected));
    }

    private static EnumModel? GetEnum(GeneratorSyntaxContext context)
    {
        if (context.Node is not EnumDeclarationSyntax syntax)
            return null;
        if (context.SemanticModel.GetDeclaredSymbol(syntax) is not INamedTypeSymbol symbol)
            return null;
        if (symbol.ContainingType?.ToDisplayString() != "Ciallo.Tool.ToolButton")
            return null;
        if (symbol.Name != "Type")
            return null;

        var members = ImmutableArray.CreateBuilder<MemberModel>();
        int declarationIndex = 0;
        foreach (var member in symbol.GetMembers().OfType<IFieldSymbol>())
        {
            if (!member.HasConstantValue)
                continue;

            var definition = member.GetAttributes().FirstOrDefault(static a =>
                a.AttributeClass?.ToDisplayString() == DefinitionFqn ||
                a.AttributeClass?.Name is "DefinitionAttribute" or "Definition");
            if (definition is null)
                continue;

            string iconPath = definition.ConstructorArguments.Length > 0
                ? definition.ConstructorArguments[0].Value as string ?? ""
                : "";
            string tooltip = definition.ConstructorArguments.Length > 1
                ? definition.ConstructorArguments[1].Value as string ?? ""
                : "";
            string? shortcutMember = definition.NamedArguments
                .FirstOrDefault(static p => p.Key == "ShortcutMember")
                .Value.Value as string;

            members.Add(new MemberModel(
                member.Name,
                iconPath,
                tooltip,
                shortcutMember,
                declarationIndex,
                member.Locations.Length > 0 ? member.Locations[0].SourceSpan.Start : declarationIndex));
            declarationIndex++;
        }

        return new EnumModel(members.ToImmutable());
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<EnumModel?> enums)
    {
        var model = enums.FirstOrDefault(static e => e is not null);
        if (model is null)
            return;

        var members = model.Value.Members
            .OrderBy(static m => m.SpanStart)
            .ToArray();

        var builder = new StringBuilder();
        builder.AppendLine(
            """
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Collections.Immutable;
            using Ciallo;
            using Godot;

            namespace Ciallo.Tool;

            public static partial class ToolButton
            {
                public static ImmutableArray<Descriptor> Definitions { get; } =
                [
            """);

        foreach (var member in members)
        {
            string shortcut = string.IsNullOrEmpty(member.ShortcutMember)
                ? "null"
                : $"AppHotkeys.Global.{member.ShortcutMember}";
            builder.AppendLine(
                $"        new(Type.{member.Name}, \"{Escape(member.IconPath)}\", \"{Escape(member.Tooltip)}\", {shortcut}),");
        }

        builder.AppendLine(
            """
                ];

                public static Descriptor GetDefinition(Type type) => type switch
                {
            """);

        for (int i = 0; i < members.Length; i++)
            builder.AppendLine($"        Type.{members[i].Name} => Definitions[{i}],");

        builder.AppendLine(
            """
                    _ => throw new ArgumentOutOfRangeException(nameof(type), type, null),
                };

                public static bool TryResolveHotkey(InputEventKey key, out Type type)
                {
                    foreach (var definition in Definitions)
                    {
                        if (definition.Shortcut?.IsPressedBy(key) != true) continue;

                        type = definition.Type;
                        return true;
                    }

                    type = default;
                    return false;
                }
            }
            """);

        context.AddSource("ToolButton.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private readonly struct MemberModel
    {
        public MemberModel(
            string name,
            string iconPath,
            string tooltip,
            string? shortcutMember,
            int declarationIndex,
            int spanStart)
        {
            Name = name;
            IconPath = iconPath;
            Tooltip = tooltip;
            ShortcutMember = shortcutMember;
            DeclarationIndex = declarationIndex;
            SpanStart = spanStart;
        }

        public string Name { get; }
        public string IconPath { get; }
        public string Tooltip { get; }
        public string? ShortcutMember { get; }
        public int DeclarationIndex { get; }
        public int SpanStart { get; }
    }

    private readonly struct EnumModel
    {
        public EnumModel(ImmutableArray<MemberModel> members)
        {
            Members = members;
        }

        public ImmutableArray<MemberModel> Members { get; }
    }
}
