name: Bug report
description: Report a bug in Ciallo
assignees: [ShenCiao]

body:
  - type: markdown
    attributes:
      value: |
        Please search existing issues before creating a new one.

  - type: textarea
    attributes:
      label: Version information
      description: Please specify your Ciallo version and commit hash if available.
      placeholder: "Ciallo commit: abc123def"
    validations:
      required: true

  - type: input
    attributes:
      label: System information
      description: Please specify OS, GPU model, and any relevant hardware information.
      placeholder: "Windows 11 - NVIDIA GeForce RTX 3070"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Issue description
      description: Describe your issue briefly. What doesn't work, and how do you expect it to work instead?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce the issue.
      placeholder: |
        1. Open Ciallo
        2. ...
        3. Notice the issue
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction project
      description: |
        If needed, drag and drop a .ciallo project file or write "N/A" if not applicable.
      placeholder: Attach a .ciallo project file or write "N/A" if not applicable
    validations:
      required: false