name: Feature request
description: Suggest a new feature for Ciallo
assignees: [ShenCiao]

body:
  - type: markdown
    attributes:
      value: |
        Please search existing issues to ensure this feature hasn't already been requested.

  - type: textarea
    attributes:
      label: Feature description
      description: Describe the feature you would like to see in Ciallo.
      placeholder: I would like Ciallo to have...
    validations:
      required: true