# Sourced by engine.sh after selecting the editor and its matching SDK version.
configure_csharp() {
    local package source target props cache changed=false
    mkdir -p "$state/nuget"
    for package in Godot.NET.Sdk Godot.SourceGenerators GodotSharp GodotSharpEditor; do
        source="$sharp/Tools/nupkgs/$package.$sdk.nupkg"
        target="$state/nuget/$package.$sdk.nupkg"
        [ -f "$source" ] || fail "Missing bundled package: $source"
        if [ ! -f "$target" ] || ! cmp -s "$source" "$target"; then
            cp "$source" "$target.tmp-$$"; mv -f "$target.tmp-$$" "$target"
            changed=true
        fi
    done
    for target in "$state/nuget/"*.nupkg; do
        case "$target" in *".$sdk.nupkg") ;; *) rm -f "$target" ;; esac
    done
    if [ -f "$project/global.json" ]; then
        jq -e '."ciallo-local-engine" == true' "$project/global.json" >/dev/null ||
            fail 'Ciallo/global.json is not generated by engine setup; move it before changing engines.'
    fi
    if $local_mode; then
        jq --arg sdk "$sdk" '."msbuild-sdks"."Godot.NET.Sdk" = $sdk | ."ciallo-local-engine" = true' \
            "$root/global.json" | write_file "$project/global.json"
        props="$sharp/Tools/LocalDevelopment/Godot.LocalDevelopment.props"
        if [ -f "$props" ]; then
            printf '<Project><Import Project="%s" /></Project>\n' "$(native_path "$props" | jq -Rr '@html')" |
                write_file "$project/.godot/mono/local_sdk.props"
        else rm -f "$project/.godot/mono/local_sdk.props"; fi
        # Local builds can replace a package without changing its Git-derived version.
        if $changed; then
            cache=${NUGET_PACKAGES:-$HOME/.nuget/packages}
            [ "$os" != windows ] || cache=$(cygpath -u "$cache")
            if [ -d "$cache" ]; then
                cache=$(CDPATH= cd "$cache" && pwd -P)
                for package in godot.net.sdk godot.sourcegenerators godotsharp godotsharpeditor; do
                    target="$cache/$package/$sdk"
                    [ ! -L "$cache/$package" ] && [ ! -L "$target" ] || fail 'Unexpected link in NuGet package cache.'
                    [ ! -d "$target" ] || rm -rf -- "$target"
                done
            fi
        fi
    else
        rm -f "$project/global.json" "$project/.godot/mono/local_sdk.props"
    fi
}
