<Project Sdk="Godot.NET.Sdk">
    <PropertyGroup>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <LangVersion>default</LangVersion>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <IsTestProject>true</IsTestProject>
        <TestFramework>GdUnit4</TestFramework>
        <VSTestTestAdapterPath>none</VSTestTestAdapterPath>
        <RunSettingsFilePath>$(MSBuildProjectDirectory)/.runsettings</RunSettingsFilePath>
        <RunSettingsFilePath Condition="'$(GODOT_BIN)' == '' And Exists('$(MSBuildProjectDirectory)/.runsettings.local')">$(MSBuildProjectDirectory)/.runsettings.local</RunSettingsFilePath>
        <!--Disable warning of invalid/incompatible GodotSharp version-->
        <NoWarn>NU1605</NoWarn>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Frent" Version="0.7.1-beta" />
        <PackageReference Include="GodotSharp.SourceGenerators" Version="2.7.0-260308-1543.Release" />
        <PackageReference Include="Humanizer" Version="3.0.10" />
        <PackageReference Include="MessagePack" Version="3.1.7" />
        <PackageReference Include="MessagePackGodot" Version="1.0.2" />
        <PackageReference Include="DuckDB.NET.Data.Full" Version="1.5.3" />
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.8" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
        <PackageReference Include="gdUnit4.api" Version="5.1.0-rc5" />
        <PackageReference Include="gdUnit4.test.adapter" Version="3.1.1" />
        <PackageReference Include="gdUnit4.analyzers" Version="1.0.0">
            <PrivateAssets>none</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="ObservableCollections.R3" Version="3.3.4" />
        <PackageReference Include="R3" Version="1.3.1" />
        <PackageReference Include="Stateless" Version="5.20.1" />
        <PackageReference Include="System.Management" Version="10.0.8" />
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Localization\*.csv" />
        <None Include="**\*.gdshader" />
        <AdditionalFiles Include="**\*.tscn">
            <DependentUpon Condition="Exists('%(RootDir)%(Directory)%(Filename).cs')">%(Filename).cs</DependentUpon>
        </AdditionalFiles>
        <AdditionalFiles Include="project.godot" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="SourceGeneration\**" />
        <Compile Remove="InkStrokeModeler\**" />
        <Compile Remove="InkStrokeModeler.Tests\**" />
        <Compile Remove=".godot\**" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Remove="SourceGeneration\**" />
        <EmbeddedResource Remove="InkStrokeModeler\**" />
        <EmbeddedResource Remove="InkStrokeModeler.Tests\**" />
        <EmbeddedResource Remove=".godot\**" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="SourceGeneration\SourceGeneration.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="InkStrokeModeler\InkStrokeModeler.csproj" />
        <!-- The .NET SDK removes RuntimeIdentifier when building referenced libraries. -->
        <ProjectReference Include="..\thirdparty\Facepunch.Steamworks.csproj"
                          AdditionalProperties="FacepunchRuntimeIdentifier=$(RuntimeIdentifier)" />
    </ItemGroup>

    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
        <DefineConstants>OS_WINDOWS</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
        <DefineConstants>OS_LINUX</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('FreeBSD'))">
        <DefineConstants>OS_FREEBSD</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
        <DefineConstants>OS_MAC</DefineConstants>
    </PropertyGroup>

    <Import Project="$(GodotProjectDir).godot/mono/local_sdk.props" Condition="Exists('$(GodotProjectDir).godot/mono/local_sdk.props')" />
</Project>
