using System;
using Godot;

namespace Ciallo.Tool;

public readonly record struct LiquifyDab(
    Vector2 Center,
    Vector2 Delta,
    float Radius,
    float Strength,
    float Pressure)
{
    // Vector2.Inf marks the button-down dab: Push ignores it, while scalar/radial modes
    // treat it as one unit of movement so clicking still has an effect.
    public bool IsInitialDab()
    {
        return Mathf.IsInf(Delta.X) || Mathf.IsInf(Delta.Y);
    }
}

/// <remarks>
/// Generated by GPT-5.5 by asking it to learn from the code of Blender grease pencil's "Sculpt" tool.
/// </remarks>
public static class LiquifySculpt
{
    // Per-dab radial scaling for Expand/Pinch. With influence ≈ 1, peak per-dab
    // displacement is (1/5)^2 = 4%, so a drag accumulates smoothly instead of
    // snapping the geometry on a single dab.
    private const float RadialEffectScale = 1f / 5f;
    // Log-radius change per unit of brush influence and pointer travel. Applying
    // it in log space makes thickness changes proportional and reversible.
    private const float ThicknessEffectScale = 1f / 10f;

    // This is intentionally endpoint-dab sculpting, not true segment integration.
    // Delta.Length() scales non-push effects to approximate path-length invariance,
    // while Influence still uses distance to the current dab center. At stable
    // 60-100 Hz input this keeps the algorithm simple and visually close enough.
    // A real segment integral would need capsule culling, closest-point falloff,
    // and radial centers taken from the segment instead of from dab.Center.

    public static Vector2 ApplyPosition(LiquifyMode mode, Vector2 position, LiquifyDab dab)
    {
        float influence = Influence(position, dab);
        if (influence <= 0f)
            return position;

        return mode switch
        {
            LiquifyMode.Push => Push(position, dab, influence),
            LiquifyMode.Expand => Expand(position, dab.Center, influence, StepScale(dab)),
            LiquifyMode.Pinch => Pinch(position, dab.Center, influence, StepScale(dab)),
            _ => throw new ArgumentOutOfRangeException(nameof(mode), mode, null)
        };
    }

    public static float ApplyThickness(LiquifyMode mode, Vector2 position, float radius, LiquifyDab dab)
    {
        float influence = Influence(position, dab);
        if (influence <= 0f)
            return radius;

        float logScale = influence * ThicknessEffectScale * StepScale(dab);
        return mode switch
        {
            LiquifyMode.Thicken => radius * Mathf.Exp(logScale),
            LiquifyMode.Thin => radius * Mathf.Exp(-logScale),
            _ => throw new ArgumentOutOfRangeException(nameof(mode), mode, null)
        };
    }

    public static float Influence(Vector2 position, LiquifyDab dab)
    {
        float distance = position.DistanceTo(dab.Center);
        if (distance > dab.Radius)
            return 0f;

        float falloff = SmoothFalloff(distance / dab.Radius);
        return dab.Strength * NormalizePressure(dab.Pressure) * falloff;
    }

    private static Vector2 Push(Vector2 position, LiquifyDab dab, float influence)
    {
        if (dab.IsInitialDab())
            return position;

        return position + dab.Delta * influence;
    }

    private static Vector2 Expand(Vector2 position, Vector2 brushCenter, float influence, float stepScale)
    {
        float scaled = influence * RadialEffectScale;
        float factor = Mathf.Pow(1f + scaled * scaled, stepScale);
        return brushCenter + (position - brushCenter) * factor;
    }

    private static Vector2 Pinch(Vector2 position, Vector2 brushCenter, float influence, float stepScale)
    {
        float scaled = influence * RadialEffectScale;
        float factor = Mathf.Pow(1f - scaled * scaled, stepScale);
        return brushCenter + (position - brushCenter) * factor;
    }

    private static float StepScale(LiquifyDab dab) => dab.IsInitialDab() ? 1f : dab.Delta.Length();

    private static float SmoothFalloff(float normalizedDistance)
    {
        float t = Mathf.Clamp(normalizedDistance, 0f, 1f);
        return 1f - t * t * (3f - 2f * t);
    }

    private static float NormalizePressure(float pressure) => pressure <= 0f ? 1f : pressure;
}
