name: "godot-ci export"
on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.5.stable.mono
  EXPORT_NAME: Ciallo
  PROJECT_PATH: ./Ciallo

jobs:
  export-windows:
    name: Build
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:mono-4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          lfs: true
          submodules: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
      - name: Import resources once
        continue-on-error: true
        run: |
          cd $PROJECT_PATH
          godot --headless --verbose --import
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"
          
